version: '3.8'

services:
  website:
    image: my-hugo-site  # Имя нашего образа
    container_name: portfolio-site
    restart: unless-stopped
    ports:
      - "80:80"  # Открываем порт 80 на сервере
    networks:
      - portfolio-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - portfolio-net

volumes:
  prometheus_data:

networks:
  portfolio-net:
    driver: bridge