global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - ob_name: 'website-availability'
    metrics_path: /  # Проверяем главную страницу
    static_configs:
      - targets: ['website:80']